# Generated by Django 4.2.3 on 2023-08-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cart',
            name='product_img',
            field=models.ImageField(upload_to='cart/'),
        ),
    ]
